---
- name: Get Azure VM Info
  azure.azcollection.azure_rm_virtualmachine_info:
  register: instance_info

- name: Set the un-tagged to vars
  ansible.builtin.set_fact:
    untagged_instances: "{{ instance_info.vms | selectattr('tags', 'equalto', {}) | map(attribute='name') | list }}"
  when: azure_savings_untagged
    
- name: Set the missing owner to vars
  ansible.builtin.set_fact:
    missing_owner: "{{ instance_info.vms | selectattr('tags.owner', 'undefined') | map(attribute='name') | list }}"
  when: azure_savings_no_owner

- name: Display un-tagged instances
  ansible.builtin.debug:
    msg: "{{ untagged_instances }}"
  when: azure_savings_untagged

- name: Terminate every un-tagged instance
  azure.azcollection.azure_rm_virtualmachine:
    name: "{{ item }}"
    resource_group: "{{ hostvars[item].resource_group }}"
    state: absent
  loop: "{{ untagged_instances }}"
  when: 
    - untagged_instances | default('[]') | length  > 0
    - azure_savings_perform_savings
    - azure_savings_untagged

- name: Display instances missing owner
  ansible.builtin.debug:
    msg: "{{ missing_owner }}"
  when: azure_savings_no_owner

- name: Stop every non owner instance
  azure.azcollection.azure_rm_virtualmachine:
    name: "{{ item }}"
    resource_group: "{{ hostvars[item].resource_group }}"
    started: false
  loop: "{{ missing_owner }}"
  when: 
    - missing_owner | default('[]') | length  > 0
    - azure_savings_perform_savings
    - azure_savings_no_owner
